FROM --platform=linux/x86_64 ruby:2.6.2-alpine

ENV LANG C.UTF-8
WORKDIR /app

ENV BUNDLE_JOBS=32 \
    BUNDLE_WITHOUT='production:staging'

# chrome をインストール
RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add && \
    echo 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main' | tee /etc/apt/sources.list.d/google-chrome.list && \
    apk add update && \
    apk add install -y google-chrome-stable

COPY Gemfile Gemfile.lock /app/
RUN bundle install

COPY package.json yarn.lock /app/
RUN yarn install

COPY . /app

ENTRYPOINT [ "./entrypoint.sh" ]

