version: '3'
services:
  db:
    platform: linux/x86_64
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql:delegated
    environment:
      TZ: Asia/Tokyo
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_ROOT_HOST: '%'
    ports:
      - "6603:3306"
    healthcheck:
      test: "mysqladmin ping -u root"
      interval: 3s
      timeout: 1s
      retries: 5
  redis:
    image: redis:latest
    volumes:
      - redis_data:/data
    ports:
      - "6666:6379"
  web: &app_base
    build:
      context: .
      dockerfile: "Dockerfile.dev"
    image: web_image
    command: /bin/bash -c "rm -rf ./tmp/pids/server.pid && rm -rf ./public/packs && bundle exec rails s -p 3000 -b '0.0.0.0'"
    env_file:
      - "./.env.docker.dev"
    volumes:
      - .:/myapp:cached
      - bundle:/usr/local/bundle:delegated
      - node_modules:/myapp/node_modules:delegated
      # exclude volumes
      - /myapp/log
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true
    depends_on:
      - db
      - redis
    environment:
      DATABASE_HOST: db
      DATABASE_USER: root
      DATABASE_PASSWORD: ""
      DATABASE_PORT: 3306
      REDIS_URL: redis://redis:6379
  worker:
    <<: *app_base
    command: ["bundle", "exec", "sidekiq", "-C", "config/sidekiq.yml"]
    ports:
      - "9999:3000"
volumes:
  mysql_data:
  redis_data:
  bundle:
  node_modules:

