FROM --platform=linux/x86_64 ruby:2.6.2

ENV LANG C.UTF-8

RUN set -x && curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - && \
    echo 'deb http://dl.yarnpkg.com/debian/ stable main' > /etc/apt/sources.list.d/yarn.list
RUN set -x && apt-get update -qq && \
    apt-get install -yq build-essential nodejs yarn

# chrome をインストール
RUN curl -L -o google-chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb \
    && dpkg -i google-chrome.deb \
    && sed -i 's|HERE/chrome\"|HERE/chrome\" --disable-setuid-sandbox|g' /opt/google/chrome/google-chrome \
    && rm google-chrome.deb

WORKDIR /app
ENV BUNDLE_JOBS=32 \
    BUNDLE_WITHOUT='production:staging'

COPY Gemfile Gemfile.lock /app/
RUN bundle install

COPY package.json yarn.lock /app/
RUN yarn install

COPY . /app

ENTRYPOINT [ "./entrypoint.rb" ]
